### ISSUE TITLE
TypeError: unhashable type: 'HighMediumLow_1_0'

### ISSUE THREAD

**Issue by sean-macfarlane** [oasis-open/cti-stix-elevator#93] opened 2018-01-22 21:53 UTC
I'm trying to elevate a STIX v1.1.1 xml file and I keep getting this error

```
Traceback (most recent call last):
  File "server.py", line 20, in <module>
    results = elevate_file("test.xml")
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/stix2elevator/__init__.py", line 44, in elevate_file
    container = stixmarx.parse(fn)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/stixmarx/__init__.py", line 23, in parse
    stix_package = parser.parse_xml(xml_input, encoding)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/stixmarx/parser.py", line 295, in parse_xml
    return parser.parse()
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/stixmarx/parser.py", line 283, in parse
    encoding=self._encoding
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/stix/core/stix_package.py", line 234, in from_xml
    return entity_parser.parse_xml(xml_file, encoding=encoding)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/parser.py", line 187, in parse_xml
    entity = self.get_entity_class(xml_root_node.tag).from_obj(entity_obj)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/entities.py", line 377, in from_obj
    val = transformer.from_obj(val)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/entities.py", line 375, in from_obj
    val = [transformer.from_obj(x) for x in val]
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/entities.py", line 375, in <listcomp>
    val = [transformer.from_obj(x) for x in val]
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/entities.py", line 377, in from_obj
    val = transformer.from_obj(val)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/entities.py", line 377, in from_obj
    val = transformer.from_obj(val)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/entities.py", line 185, in from_obj
    return klass.from_obj(cls_obj)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/entities.py", line 381, in from_obj
    signals.emit("Entity.created.from_obj", entity, cls_obj)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/mixbox/signals.py", line 214, in emit
    func(*args, **kwargs)
  File "/home/sean/CLAW_TAXII_Service/venv/lib/python3.5/site-packages/stixmarx/parser.py", line 103, in _handle_entity_created
    self._entities.add(entity)
TypeError: unhashable type: 'HighMediumLow_1_0'
```

**Comment by gtback** [comment] 2018-01-23 14:58
Thanks, @sean-macfarlane ! Are you using Python 3? I think this error is due to the fact that we need to define `VocabString.__hash__` in the stix111 branch of python-stix. We'll try to take a closer look soon.

**Comment by sean-macfarlane** [comment] 2018-01-23 20:15
Yes python 3.5.2

**Comment by sean-macfarlane** [comment] 2018-01-23 20:21
I did as the README said and installed python-stix 1.1.1 package first  `pip install 'stix<1.2'` 
But if I just install python-stix 1.2.0 via `pip install stix` I do not get this error. So the error is as you said in version 1.1.1 of python-stix.

**Comment by gtback** [comment] 2018-01-24 17:50
Yes, this is a known bug in python-stix 1.1.1.x and Python 3. I just created an issue there to solve it, but will leave this open until we can verify that the new release will also fix this error.

**Comment by emmanvg** [comment] 2018-02-28 21:39
@sean-macfarlane, just as an update. This issue has been resolved in python-stix. The fix should be available in the next release. I am OK with closing this issue unless there is something else realted to the `cti-stix-elevator`. Once the new version for stix 1.1.1 is available this should work as intended.

**Comment by emmanvg** [comment] 2018-03-06 19:15
The new releases are out. You should be able to upgrade the `stix` library to `1.1.1.10`. @rpiazza can you close this?

**Comment by gtback** [comment] 2018-03-12 15:19
@sean-macfarlane, if you're still having problems after updating to the newer python-stix, feel free to re-open.

**Closed** 2018-03-12 15:18 UTC
